### PR TITLE
lander/joinbutton comments/fixes

### LINKED ISSUE #20: Landing Banner + Join Us button
Image

Create the Landing banner component. Make the component in the a new file called landing.tsx in src/components/home

Also create the Join Us button in the joinUs.tsx file in the src/components/home directory

Image

### PR DESCRIPTION
**Pull request by varunm532**
image
image
image
when clicking on join button:
image

### CODE REVIEW

File: src/app/page.tsx [hunk 1]
```diff
@@ -1,8 +1,12 @@
 import OurMissionComponent from "@/components/home/ourMission";
+import Lander from "@/components/home/lander";
+import JoinUs from "@/components/home/joinUs";
 
 const Home = () => {
   return (
-    <div className="flex h-screen w-screen items-center justify-center">
+    <div className="h-screen w-screen grid-cols-1 grid-rows-3 flex-col items-center justify-center">
+      <Lander />
+      <JoinUs />
```
Comment (wesleylwu) [inline src/app/page.tsx]: move the styling inside the component. we usually don't want any styling in the page.tsx files. also move the join us under the OurMissionComponent

File: src/components/home/joinUs.tsx [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+    console.log("Join us clicked");
+    window.location.href = "/join";
+  };
+  //giving picture from figma button functionality
+  return (
+    <div className="bg-color-redefined-cream flex justify-center">
+      {/*giving button functionality to join button */}
+      <button onClick={handleClick}>
+        <Image src={Picture} alt="Join us Button" />
+      </button>
```
Comment (wesleylwu) [inline src/components/home/joinUs.tsx]: instead of the image, you can make the button just with tailwindcss styling. try using something like `<button className="bg-redefined-cream border-redefined-olive border-3 w-40 h-20 rounded-full">` and this will create the button style (you may have to play around with it to make it look closer to the figma). to make it link to something, you can use `<Link
        href="https://discord.com/invite/GrU6QAHJJ"
        target="_blank"
      >` directly above the button tag to connect it to the discord!

File: src/components/home/joinUs.tsx [hunk 3]
```diff
@@ -0,0 +1,22 @@
+"use client";
+
+import Image from "next/image";
+import Picture from "@/public/join_us.png";
+const JoinUs = () => {
+  //things to do when button is clicked--needs to be changed depending on functionality--placeholder functionality currecntly
+  const handleClick = () => {
+    console.log("Join us clicked");
+    window.location.href = "/join";
+  };
```
Comment (wesleylwu) [inline src/components/home/joinUs.tsx]: remove this; reference the comment below

File: src/components/home/joinUs.tsx [hunk 4]
```diff
@@ -0,0 +1,22 @@
+"use client";
```
Comment (wesleylwu) [inline src/components/home/joinUs.tsx]: you can remove these. add `import Link from "next/link";` because you will be using the Link tag

**Review by wesleylwu — CHANGES_REQUESTED** [review]
good work for your first issue! just some comments:
- most "simple" styled components can be made with TailwindCSS styling rather than importing an image (see comments below)
- please remove comments in your components as well

**Comment by varunm532** [comment]
image
image
join us when clicked
image

File: src/components/home/joinUs.tsx [hunk 5]
```diff
@@ -0,0 +1,17 @@
+import Link from "next/link";
+const JoinUs = () => {
```
Comment (Kevin-Pember) [inline src/components/home/joinUs.tsx:2]: Now that you have implemented the component remove `public/join_us.png`

File: src/components/home/joinUs.tsx [hunk 6]
```diff
@@ -0,0 +1,17 @@
...
+  return (
+    <Link href="https://discord.com/invite/GrU6QAHJJ" target="_blank">
+      <div className="bg-color-redefined-cream flex justify-center">
+        {/*giving button functionality to join button */}
+
+        <button className="bg-redefined-cream border-redefined-olive h-129px font-redefined-albert w-1/4 rounded-[102px] border-[13px] text-[64px] font-[800] text-[#9E4325] italic">
+          {" "}
```
Comment (Kevin-Pember) [inline src/components/home/joinUs.tsx]: Use [padding](https://tailwindcss.com/docs/padding) not whitespace

File: src/components/home/lander.tsx [hunk 7]
```diff
@@ -0,0 +1,12 @@
+import Image from "next/image";
+import Picture from "@/public/Landing_Pic.png";
+const Lander = () => {
+  return (
+    //adds landing picture and makes it so that the picture's width is the entire screen
+    <div className="flex w-screen justify-center">
+      <Image className="w-full" src={Picture} alt="Landing Picture" />
```
Comment (Kevin-Pember) [inline src/components/home/lander.tsx]: Ok rather then having the image contain both the group photo and the text "redefined at ucr" split it into two elements. The group photo being one element and the text "redefined at UCR". The text boarder might be a little difficult to implement you might just want to get the text as an svg and center that in the middle of the group photo. This way if redefined ever wants to update that photo we don't have recreate the text

**Review by Kevin-Pember — CHANGES_REQUESTED** [review]
Good Work, just a few changes

**Comment by varunm532** [comment]
made changes -- seperated text and picture 
image
and removed the spaceing 
image
image
when clicked

**Comment by varunm532** [comment]
fixed merge isses

File: src/components/home/ourMission.tsx [hunk 8]
```diff
@@ -19,6 +20,10 @@ const OurMissionComponent = () => {
           create a lasting impact.
         </p>
       </div>
+      {/*calling button component*/}
+      <div className="w-full gap-2 pb-15">
```
Comment (Kevin-Pember) [inline src/components/home/ourMission.tsx]: As Wesley said 
> move the styling inside the component. we usually don't want any styling in the page.tsx files.

File: src/components/home/lander.tsx [hunk 9]
```diff
@@ -0,0 +1,26 @@
...
+import Picture from "@/public/Landing_Pic.png";
+import Picture_Text from "@/public/Landing_pic_text.svg";
+const Lander = () => {
+  return (
+    //adds landing picture and makes it so that the picture's width is the entire screen
+    <div>
+      <div className="flex w-screen justify-center">
+        {/* split svg text and landing banner picture */}
+        <Image
+          className="absolute mt-[200px] flex w-1/3 items-center justify-center"
```
Comment (Kevin-Pember) [inline src/components/home/lander.tsx]: This isn't a valid way to center text, it might work for your screen but not other people. 

Image

To fix it make the parent div a grid with only one row and col then set the z parameter for the text higher than the landing picture. After that make sure that both the landing picture and the landing text are in the same grid column and row. That should center the text

File: src/components/home/lander.tsx [hunk 10]
```diff
@@ -0,0 +1,26 @@
+import Image from "next/image";
+import Picture from "@/public/Landing_Pic.png";
+import Picture_Text from "@/public/Landing_pic_text.svg";
+const Lander = () => {
+  return (
+    //adds landing picture and makes it so that the picture's width is the entire screen
+    <div>
+      <div className="flex w-screen justify-center">
```
Comment (Kevin-Pember) [inline src/components/home/lander.tsx]: Can just be one div

**Review by Kevin-Pember — CHANGES_REQUESTED** [review]
Good progress but still have some things to handle.

**Comment by varunm532** [comment]
image
image

**Review by wesleylwu — APPROVED** [review]
lgtm!

**Review by Kevin-Pember — APPROVED** [review]
LGTM!
